language: node_js
services:
- rabbitmq
node_js:
- '10'
- '8'
- '6'
notifications:
  slack:
    secure: I+jHVg47h2vW9ZjXWMOKc1+HZcIO0RmlKMJSN/Ra3+Svos44YiTKrRgsQ8XIkfO3Kr4OQM+UG9Inbe3lSzRlPN8j/j3RP1ms4E3pzaYHeZMmIrI7njbXHzMK40+Qzbpq10CbxNh3N7F+H+vbTGOWbXWakwqJDKdB6I/L0weQB8EGv5rZ6GEvksmKILbS2z0I4EWCuU/wkK9Ej7SSHwW+WZTEPj+b7Em2iJN5JC/wZnUaQxonP3LGXg8Ydy18/i0L+iw6yhswVHWASQx6fosW3rirGrEsjQ8Ty7YQq/GLHplONpLDGb6NLbjDlPAfN2TcIJFotT6uiPU3zwcm7g4aC3RVsjfOhAXmlM8JripDtznqL9zGJcNsp6/9fZCZpC2p7LsVpzaBUg+RaWrr8kbKXn+eTdtFGXYTDw8fqJiLoxwInkIkcfZTkeH5T8Q+66C8TOUcPbOi0seBLueb/+0VQHylF4IGECJXEaJKeDmy93mIpjepXF3nGn2KRLQDG+yIonEKbN0DkOW6VdhtOeOPdRbE+qWx5awM+y3JHitEHxZNOxRTUqSf5sO0emdKHB4a/76hTt6i/F68oG6QDlw6+4kcXdHpecIBC17TZGMgFy4blJca8sqGNUJBfCfUEgKCzl8Du+IDOKCOWg06zvqq1iOzAIgzzGlSpwxqTZ6qdng=
deploy:
  provider: npm
  email: npm@loke.com.au
  api_key:
    secure: L2sjJ8REsBOv0Olj/CHqLsCSUnW5mfTQRcS9ruJbR7qTTR7XpWbW3B4Ec/Rm+t0KCaiXR4hyPoC1TnlhQxnIavQGNkXIidMGyC9GWTe7ODolQJAllLM2ZSk9AEqvhGwswHMazd2ynFQTUrHz249YBoTHC2FZ6x5wQ2naQLFGtQSicjhCz26ezDHafDuPpaPH4QpbTdD5THjyU+MAyl5SQ1NDVw51SZr5NPxkIHBVrZ0LG/OruAWts/MKp4tGMfqgn7uLTZ4XjL8sR+bmojzLmHzBwnmrlC5i5o8IS1OvZCREdT342RkUYQgbJXk64Y1mrvvHIKlDiMxA6Ll2fDXA4iKb8Vf/L5Ehw/ocdbz3vqWyfQ8PR2A247ZSFzaNWV3lFN0PQEtqYhuAW4EEE+lfYhZyUjkDLeVbrsUbPgGcPuh7i4+tAJXwPLmpCqn+P3MsvQBxAXeL7DwcNVYO6Uo5j74MXJAi5dPS/Zfwsh7s7qBnfPhxLujzYvOXvHYvwqGEHIwbfa33wb0bz6isRyCYtjrBagMWdf5JkGvmJCAeP8e2Gbj3I4q7rR7zkiadvIIB3GpfW561uLC7HyQvsYyWxfyc7NdCVTA8sfWitLUPjBTTHt6CUIna4ADgUAxw2r56+q9vj3sUEaDsNP5gCA51MVtDg4YswJezDU+10sh6yxs=
  on:
    tags: true
    repo: LOKE/loke-ipc
