language: node_js
services:
- rabbitmq
node_js:
- '5'
- '4'
- '0.12'
- '0.11'
- '0.10'
notifications:
  slack:
    secure: I+jHVg47h2vW9ZjXWMOKc1+HZcIO0RmlKMJSN/Ra3+Svos44YiTKrRgsQ8XIkfO3Kr4OQM+UG9Inbe3lSzRlPN8j/j3RP1ms4E3pzaYHeZMmIrI7njbXHzMK40+Qzbpq10CbxNh3N7F+H+vbTGOWbXWakwqJDKdB6I/L0weQB8EGv5rZ6GEvksmKILbS2z0I4EWCuU/wkK9Ej7SSHwW+WZTEPj+b7Em2iJN5JC/wZnUaQxonP3LGXg8Ydy18/i0L+iw6yhswVHWASQx6fosW3rirGrEsjQ8Ty7YQq/GLHplONpLDGb6NLbjDlPAfN2TcIJFotT6uiPU3zwcm7g4aC3RVsjfOhAXmlM8JripDtznqL9zGJcNsp6/9fZCZpC2p7LsVpzaBUg+RaWrr8kbKXn+eTdtFGXYTDw8fqJiLoxwInkIkcfZTkeH5T8Q+66C8TOUcPbOi0seBLueb/+0VQHylF4IGECJXEaJKeDmy93mIpjepXF3nGn2KRLQDG+yIonEKbN0DkOW6VdhtOeOPdRbE+qWx5awM+y3JHitEHxZNOxRTUqSf5sO0emdKHB4a/76hTt6i/F68oG6QDlw6+4kcXdHpecIBC17TZGMgFy4blJca8sqGNUJBfCfUEgKCzl8Du+IDOKCOWg06zvqq1iOzAIgzzGlSpwxqTZ6qdng=
deploy:
  provider: npm
  email: npm@loke.com.au
  api_key:
    secure: Kz8n3eRgQfmZr/Pl7rc6jNfD+DAXSCPUpMJW4Oewl2MswSjT29iQ6VsgiPQKsEbzoFfw5yUdrfrrIKxp8c1i/P5eNB+s5I+YMQ/LVNhErqsFqj4a3gf3Whmo6KQstZtj0/hrVuHes0oMV13RV0xkxeq0fjhcgNICVqz3Sa0Zxcz+4nJ5LQrbUkv5E5o1knsV6z+D2R2qIzSr/zpkqSAttOIHyq1RigLNPwr9HUOUONgbbHCD+17Tp2a+fKDkOVlKeZWdSnClkKQfzHQaCbOJCxu6xckbe4kdPKi3NKH5aCOuAugFBe9GdDRHyd9e/mpUj6tMk9+SQ+tpzRTXfVzaEizJLy7YGhHqIspaG/12AajxWtMBi3n+UgRyfkN9rM3nwNOLITJ/fAmR5Z9LdrI7Sy5HhUoqnlf8Mo/jRjzb3viBVsqOqZkiu0fmLqCZCsDHgVbL8upSckB6JfNqaMnZYwsP+inQtwDJ/XUbic6/OWyXEIgwgINJZIaonrc89OGus7SY0ErRaEl82XXRIgzGfUGr225EP6j15AuvEx9YbfnFPns+VbROXZ8KR9MgoGrKPIXt+htU8FUxwzi8LFOH4SNg4PiDPmJXiGoELuoGwsdaDZhPOTHzWB6RftPUzChIozeIEQL1z2sYLGwLmgsQDbD8WBzHU50QwmiZHxg4NMU=
  on:
    tags: true
    repo: LOKE/loke-ipc
